repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
      - id: clang-tidy
        args: [-p=./build,--header-filter=.*,--exclude-header-filter="json.h"]
      - id: cppcheck
      # example: https://github.com/ScintillaOrg/lexilla/blob/master/cppcheck.suppress
        args: [--enable=all, --inline-suppr, --error-exitcode=1, --language=c++, -I., --suppressions-list=./cppcheck.suppress]
