name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installation
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 llvm-20 clang-20 iwyu cppcheck clang-tidy
        sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
        sudo update-alternatives \
          --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-20 100 \
          --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-20 \
          --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-20
        sudo update-alternatives \
          --install /usr/bin/clang clang /usr/bin/clang-20 100

    - name: configure
      run: cmake -Bbuild -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) -DCMAKE_BUILD_TYPE=Debug -DUSE_SANITIZER="Address;Undefined"

    - name: build
      run: cmake --build build -j4
